name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1

jobs:
  test:
    name: Test Suite
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
      
      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-
      
      - name: Run tests
        run: |
          mkdir -p test-results
          cargo test --verbose > test-results/test-output.txt 2>&1 || true
          echo "Test output saved to test-results/test-output.txt"
      
      - name: Upload test results
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: test-results/
          
  examples:
    name: Run Examples
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v3
      
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        
      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-
      
      - name: Run examples
        run: |
          mkdir -p example-results
          for example in examples/*.rs; do
            name=$(basename $example .rs)
            echo "Running example: $name"
            echo "----------------------------------------"
            if cargo run --example $name > "example-results/$name.txt" 2>&1; then
              echo "Example $name succeeded"
              echo "Output saved to example-results/$name.txt"
            else
              echo "Example $name failed!"
              echo "Output saved to example-results/$name.txt"
              exit 1
            fi
            echo "----------------------------------------"
          done
          
      - name: Upload example results
        uses: actions/upload-artifact@v3
        with:
          name: example-results
          path: example-results/
